// -----------------------------------------------------------------------------
// tb_sa_array.sv — self-checking testbench for the full 16x14 array
//
// sa_array is thin: column_pair already owns the cascade bound, the group
// alignment and the adder tree, and days 1-4 verified all of it. What is new on
// day 5 is the horizontal dimension, so that is what this testbench is aimed at.
// Three things can go wrong there, and none of them produces an implausible
// number:
//
//   1. the (row, column) -> cell mapping. 224 weights now enter through seven
//      8-bit ports. A port swapped with its neighbour, a w0/w1 swap, a reversed
//      per-port load order (which transposes the tile) and an off-by-one at a
//      group boundary are all silent. Phase 1 pins every one of the 224
//      positions individually with a one-hot weight, and because a one-hot
//      result is checked at a specific cycle, phase 1 simultaneously measures
//      the arrival time of every (row, column) pair -- which is the uniform
//      horizontal delay, per row, per column-pair, all 224 of them.
//
//   2. the per-column output skew. The activation advances one cycle per
//      column PAIR, not per output column, so LAT(j) = ROWS+2 + j/2 takes
//      seven distinct values shared pairwise, not fourteen. Phase 3 measures
//      it directly with a single pulse instead of trusting the scoreboard's
//      copy of the formula, because day 9's de-skew depths come straight off
//      this number.
//
//   3. agreement with the golden model at full scale. Phase 4 streams vectors
//      generated by model/gen_vectors.py from gemm_int8.gemm_tile_hw() -- the
//      bit-exact packed model, 25-bit A port, 48-bit truncation, borrow-
//      corrected extraction. Every other phase builds its expectation in the
//      testbench as the plain 16-term dot product, which is a check against the
//      mathematics; phase 4 is the check against the model, and it is the only
//      one that would notice the RTL and the model drifting apart on the
//      packing itself. Phase 4 also compares the file's expectation against the
//      testbench's own dot product for every vector, so a mis-indexed file read
//      cannot turn into a vacuous pass.
//
// Phase 4 needs the vector set on disk:
//
//     python3 model/gen_vectors.py       # writes build/vectors/*.hex
//
// A missing or stale set is a loud failure, not a skip: meta.hex carries a
// magic word and the geometry, and both are checked.
//
// The rest is the day-2/3/4 battery re-run at 16x14: streaming with reloads,
// the COLSUM_W corner driven to exactly +/-ROWS*PROD_MAX in both an even and an
// odd column, two flavours of en=0 stall, wgt_shift_en gating, the horizontal
// traverse measured over all seven column-pairs, and the 32-deep weight chain
// measured on all seven ports at once.
//
// House conventions that are not style preferences (docs/NOTES-tooling.md):
//   * packed arrays, and every port-connected variable assigned whole once
//     before any element-wise write
//   * `initial forever` for the clock, not `always`
//   * module-scope declarations and fixed-size arrays, no dynamic-array task
//     arguments
//   * each phase prints the failures *it* caused, not the running total. A
//     failure still bleeds up to LATMAX checks into the next phase's window,
//     because the scoreboard is that deep.
// -----------------------------------------------------------------------------
`timescale 1ns / 1ps

module tb_sa_array;
  import sa_pkg::*;

  localparam int NR     = ROWS;                 // 16 rows
  localparam int NC     = COLS;                 // 14 output columns
  localparam int NP     = NC / 2;               // 7 column-pairs = 7 DSP columns
  localparam int NW     = 2 * NR;               // 32, weight chain per port
  localparam int CLAT   = NR + 2;               // one column_pair = 18
  localparam int LATMAX = CLAT + NP - 1;        // column 13 = 24
  localparam int SETTLE = LATMAX + NR + 2;      // enough to empty the array

  localparam int TILES    = 12;
  localparam int PER_TILE = 50;

  // The COLSUM_W corner, which phase 5 must actually reach.
  localparam int BOUND  = NR * PROD_MAX;        // 260096

  // Vector-file limits. These are duplicated in model/gen_vectors.py, which
  // refuses to exceed them; Icarus will not take a dynamically sized array.
  localparam int MAXT   = 40;
  localparam int MAXV   = 2048;
  localparam int MAGIC  = 32'h00C0FFEE;

  // ---- clock / reset --------------------------------------------------------
  logic clk   = 1'b0;
  logic rst_n = 1'b0;
  logic en    = 1'b1;
  initial forever #5 clk = ~clk;            // 100 MHz. `initial forever` and
                                            // not `always`, or the lint pass
                                            // calls this sequential logic and
                                            // fires BLKSEQ.

  // ---- DUT ------------------------------------------------------------------
  logic                              wsh;
  logic signed [NP-1:0][WGT_W-1:0]   wser;     // one serial port per column-pair
  logic signed [NP-1:0][WGT_W-1:0]   wgt_o;
  logic signed [NR-1:0][ACT_W-1:0]   act;      // per-row, staggered by the tb
  logic signed [NR-1:0][ACT_W-1:0]   act_o;
  logic signed [NC-1:0][COLSUM_W-1:0] csum;

  sa_array #(
    .NROWS     (NR),
    .NCOLS     (NC),
    .GROUPS    (CASCADE_GROUPS),
    .DEPTH     (CASCADE_DEPTH),
    .K         (K_PACK),
    .GRP_W     (GROUP_W),
    .OUT_W     (COLSUM_W),
    .CLAMP_WGT (1'b1)
  ) dut (
    .clk          (clk),
    .rst_n        (rst_n),
    .en           (en),
    .wgt_shift_en (wsh),
    .wgt_in       (wser),
    .wgt_out      (wgt_o),
    .act_in       (act),
    .act_out      (act_o),
    .col_sum      (csum)
  );

  // ---- skew history: ahist[d][i] is row i's activation for the vector -------
  // ---- issued d cycles ago. Row i is driven from ahist[i][i], which is the --
  // ---- global stagger day 8's network will provide. -------------------------
  integer ahist [0:NR-1][0:NR-1];

  // ---- scoreboard, LATMAX deep and checked per column ----------------------
  // Column j is checked at depth CLAT + j/2, so one queue serves all fourteen
  // columns at their seven different latencies.
  integer expq [0:LATMAX][0:NC-1];
  bit     vldq [0:LATMAX];

  // ---- weights: W is what the host presents, E what the hardware holds -----
  integer W [0:NR-1][0:NC-1];
  integer E [0:NR-1][0:NC-1];

  integer a_vec    [0:NR-1];
  integer e_now    [0:NC-1];
  integer prev_act [0:NR-1];
  integer hq       [0:NP][0:NR-1];      // model of the horizontal traverse
  integer wq       [0:NP-1][0:NW-1];    // model of the seven weight chains

  // ---- golden-model vector set --------------------------------------------
  logic [31:0]                mmem [0:15];
  logic [7:0]                 wmem [0:MAXT*ROWS*COLS-1];
  logic [7:0]                 amem [0:MAXV*ROWS-1];
  logic signed [COLSUM_W-1:0] emem [0:MAXV*COLS-1];

  integer n_checked, n_failed, i, j, d, s, v, t, q, p, cyc;
  integer c_before, f_before;
  integer max_abs_e, max_abs_o;
  integer sv0, sv1, av;
  integer nt, pv, vi;
  // Loop variables for any loop that encloses a task call. i, j, s and d are
  // used *inside* issue/drain/flush/set_expect, so a phase that used one of
  // them as its own loop counter would have it overwritten by the first task
  // call and run exactly one iteration -- silently, and looking like a pass.
  integer oi, oj;
  integer hold_s [0:NC-1];
  integer first_at [0:NC-1];
  integer first_val [0:NC-1];
  integer n_seen [0:NC-1];
  integer mism;

  // ---------------------------------------------------------------------------
  // Helpers
  // ---------------------------------------------------------------------------
  function automatic integer clampw(input integer w);
    begin
      if (w < WGT_MIN)      clampw = WGT_MIN;
      else if (w > WGT_MAX) clampw = WGT_MAX;
      else                  clampw = w;
    end
  endfunction

  // Latency of output column j: one cycle per column-PAIR on top of the
  // column's own ROWS+2. Phase 3 measures this rather than assuming it.
  function automatic integer lat_of(input integer col);
    begin
      lat_of = CLAT + (col / 2);
    end
  endfunction

  // Expectation for whatever is in a_vec, from the weights the cells are
  // supposed to hold: the plain NR-term dot product per column. The golden
  // model has already proved the packed decomposition equals this, so the
  // testbench checks against the mathematics and not against a second copy of
  // the thing under test.
  task automatic set_expect;
    begin
      for (j = 0; j < NC; j = j + 1) begin
        e_now[j] = 0;
        for (i = 0; i < NR; i = i + 1)
          e_now[j] = e_now[j] + E[i][j] * a_vec[i];
      end
    end
  endtask

  task automatic zero_expect;
    begin
      for (j = 0; j < NC; j = j + 1) e_now[j] = 0;
    end
  endtask

  // Issue one vector: push its per-row activations into the skew history, push
  // its expectation into the scoreboard, advance one clock, then check every
  // column at its own depth.
  task automatic issue(input bit valid);
    begin
      for (s = NR-1; s > 0; s = s - 1)
        for (i = 0; i < NR; i = i + 1)
          ahist[s][i] = ahist[s-1][i];
      for (i = 0; i < NR; i = i + 1)
        ahist[0][i] = a_vec[i];

      for (i = 0; i < NR; i = i + 1)
        act[i] = ACT_W'(ahist[i][i]);

      for (s = LATMAX; s > 0; s = s - 1) begin
        for (j = 0; j < NC; j = j + 1) expq[s][j] = expq[s-1][j];
        vldq[s] = vldq[s-1];
      end
      for (j = 0; j < NC; j = j + 1) expq[0][j] = e_now[j];
      vldq[0] = valid;

      @(posedge clk);
      #1;

      for (j = 0; j < NC; j = j + 1) begin
        if (vldq[lat_of(j)]) begin
          n_checked = n_checked + 1;
          if (expq[lat_of(j)][j] > max_abs_e && (j % 2) == 0)
            max_abs_e = expq[lat_of(j)][j];
          if (-expq[lat_of(j)][j] > max_abs_e && (j % 2) == 0)
            max_abs_e = -expq[lat_of(j)][j];
          if (expq[lat_of(j)][j] > max_abs_o && (j % 2) == 1)
            max_abs_o = expq[lat_of(j)][j];
          if (-expq[lat_of(j)][j] > max_abs_o && (j % 2) == 1)
            max_abs_o = -expq[lat_of(j)][j];
          if (csum[j] !== COLSUM_W'(expq[lat_of(j)][j])) begin
            n_failed = n_failed + 1;
            if (n_failed - f_before <= 8)
              $display("  FAIL: col %0d (lat %0d) got %0d, want %0d",
                       j, lat_of(j), csum[j], expq[lat_of(j)][j]);
          end
        end
      end
    end
  endtask

  // Zero activations for long enough that nothing in flight can straddle a
  // weight change. The array is LATMAX deep plus NR of skew.
  task automatic drain;
    begin
      for (i = 0; i < NR; i = i + 1) a_vec[i] = 0;
      zero_expect();
      for (d = 0; d < SETTLE; d = d + 1) issue(1'b1);
    end
  endtask

  task automatic flush;
    begin
      for (d = 0; d < LATMAX + NR; d = d + 1) begin
        for (i = 0; i < NR; i = i + 1) a_vec[i] = 0;
        zero_expect();
        issue(1'b1);
      end
    end
  endtask

  // Shift 2*NR bytes into every one of the NP ports simultaneously. Within a
  // port the first byte presented travels furthest, so the chain fills from the
  // bottom row backwards, odd output column before even:
  //
  //   W[NR-1][2p+1], W[NR-1][2p], ... W[0][2p+1], W[0][2p]      on port p
  //
  // E records what the hardware clamp will actually store.
  task automatic load_weights;
    integer li, lp;
    begin
      for (li = 0; li < NR; li = li + 1)
        for (lp = 0; lp < NC; lp = lp + 1)
          E[li][lp] = clampw(W[li][lp]);
      wsh = 1'b1;
      for (li = NR-1; li >= 0; li = li - 1) begin
        for (lp = 0; lp < NP; lp = lp + 1) wser[lp] = WGT_W'(W[li][2*lp + 1]);
        @(posedge clk);
        #1;
        for (lp = 0; lp < NP; lp = lp + 1) wser[lp] = WGT_W'(W[li][2*lp]);
        @(posedge clk);
        #1;
      end
      wsh  = 1'b0;
      wser = '0;
    end
  endtask

  task automatic zero_weights;
    integer zi, zj;
    begin
      for (zi = 0; zi < NR; zi = zi + 1)
        for (zj = 0; zj < NC; zj = zj + 1)
          W[zi][zj] = 0;
    end
  endtask

  // ---------------------------------------------------------------------------
  // Stimulus
  // ---------------------------------------------------------------------------
  initial begin
    n_checked = 0;
    n_failed  = 0;
    c_before  = 0;
    f_before  = 0;
    max_abs_e = 0;
    max_abs_o = 0;
    mism      = 0;
    for (i = 0; i <= LATMAX; i = i + 1) begin
      vldq[i] = 1'b0;
      for (j = 0; j < NC; j = j + 1) expq[i][j] = 0;
    end

    // Whole-variable initialisation, and it has to stay whole-variable: an
    // element-wise write to a port-connected variable that has never been
    // assigned as a whole does not reach the instance under the sim named in
    // docs/NOTES-tooling.md, while Icarus simulates it correctly.
    act  = '0;
    wser = '0;
    wsh  = 1'b0;
    zero_weights();
    for (i = 0; i < NR; i = i + 1) begin
      a_vec[i]    = 0;
      prev_act[i] = 0;
      for (d = 0; d < NR; d = d + 1) ahist[d][i] = 0;
      for (d = 0; d <= NP; d = d + 1) hq[d][i] = 0;
    end
    for (j = 0; j < NC; j = j + 1) begin
      e_now[j]  = 0;
      hold_s[j] = 0;
      for (i = 0; i < NR; i = i + 1) E[i][j] = 0;
    end
    for (p = 0; p < NP; p = p + 1)
      for (i = 0; i < NW; i = i + 1) wq[p][i] = 0;

    $display("=========================================================");
    $display(" tb_sa_array : %0d rows x %0d cols = %0d column-pairs", NR, NC, NP);
    $display("   %0d DSPs, %0d MACs/cycle, chain %0d deep x %0d ports",
             NR*NP, NR*NC, NW, NP);
    $display("   latency %0d..%0d (one cycle per column-PAIR), |colsum| <= %0d",
             lat_of(0), lat_of(NC-1), BOUND);
    $display("=========================================================");

    repeat (4) @(posedge clk);
    rst_n = 1'b1;
    repeat (2) @(posedge clk);
    #1;

    // =========================================================================
    // Phase 1: one-hot placement over all NR*NC = 224 weight positions.
    //
    // A single weight of 1 at (i, j), everything else zero, and distinct
    // per-row activations. Then column j must read back exactly row i's
    // activation and every other column must read zero -- and it must do so at
    // cycle lat_of(j), because the scoreboard checks each column at its own
    // depth. So this phase pins both the placement and the timing of all 224
    // cells. A swapped pair of weight ports, a w0/w1 swap, a reversed load
    // order, a lost or duplicated cell at a group boundary, and a row whose
    // horizontal delay differs from its neighbours' all die here.
    // =========================================================================
    c_before = n_checked;
    f_before = n_failed;
    for (oi = 0; oi < NR; oi = oi + 1) begin
      for (oj = 0; oj < NC; oj = oj + 1) begin
        drain();
        zero_weights();
        W[oi][oj] = 1;
        load_weights();

        for (v = 0; v < 6; v = v + 1) begin
          for (q = 0; q < NR; q = q + 1)
            a_vec[q] = $urandom_range(0, 255) - 128;
          set_expect();
          issue(1'b1);
        end
        flush();
      end
    end
    $display("[1] one-hot placement    : %0d checks, %0d fail",
             n_checked - c_before, n_failed - f_before);

    // =========================================================================
    // Phase 2: randomised streaming with reloads between tiles. Steady state --
    // a complete 16x14 tile of dot products issued every cycle.
    // =========================================================================
    c_before = n_checked;
    f_before = n_failed;
    for (t = 0; t < TILES; t = t + 1) begin
      drain();
      for (i = 0; i < NR; i = i + 1)
        for (j = 0; j < NC; j = j + 1)
          W[i][j] = (($urandom_range(0, 9) == 0) ? -128
                                                 : $urandom_range(0, 254) - 127);
      load_weights();

      for (v = 0; v < PER_TILE; v = v + 1) begin
        for (i = 0; i < NR; i = i + 1)
          a_vec[i] = (v % 3 == 0) ? -128 : $urandom_range(0, 255) - 128;
        set_expect();
        issue(1'b1);
      end
      flush();
    end
    $display("[2] streaming + reload   : %0d checks, %0d fail",
             n_checked - c_before, n_failed - f_before);

    // =========================================================================
    // Phase 3: the per-column latency, measured rather than assumed.
    //
    // All weights 1, one all-ones vector into an empty pipeline, then zeros.
    // Column j must go non-zero exactly once, with the value NR, at issue index
    // lat_of(j) = ROWS+2 + j/2.
    //
    // This is the number day 9's de-skew depths come from, and the reason it is
    // measured here is that it is NOT (COLS-1-j): the activation advances one
    // cycle per column-PAIR, because a DSP serves two output columns. Columns
    // 2p and 2p+1 arrive together. If day 9 is built for fourteen distinct
    // depths it will de-skew an array that does not exist.
    // =========================================================================
    c_before = n_checked;
    f_before = n_failed;
    drain();
    for (i = 0; i < NR; i = i + 1)
      for (j = 0; j < NC; j = j + 1) W[i][j] = 1;
    load_weights();

    for (j = 0; j < NC; j = j + 1) begin
      n_seen[j]    = 0;
      first_at[j]  = -1;
      first_val[j] = 0;
    end
    for (cyc = 0; cyc < LATMAX + NR + 6; cyc = cyc + 1) begin
      for (i = 0; i < NR; i = i + 1) a_vec[i] = (cyc == 0) ? 1 : 0;
      zero_expect();
      issue(1'b0);                       // this phase does its own checking
      for (j = 0; j < NC; j = j + 1) begin
        if (csum[j] !== COLSUM_W'(0)) begin
          n_seen[j] = n_seen[j] + 1;
          if (first_at[j] < 0) begin
            first_at[j]  = cyc;
            first_val[j] = csum[j];
          end
        end
      end
    end
    for (j = 0; j < NC; j = j + 1) begin
      n_checked = n_checked + 3;
      if (n_seen[j] !== 1) begin
        n_failed = n_failed + 1;
        $display("  FAIL: col %0d went non-zero %0d times, want exactly 1 (the pulse smeared)",
                 j, n_seen[j]);
      end
      if (first_at[j] !== lat_of(j)) begin
        n_failed = n_failed + 1;
        $display("  FAIL: col %0d arrived at cycle %0d, want %0d (= ROWS+2 + %0d/2)",
                 j, first_at[j], lat_of(j), j);
      end
      if (first_val[j] !== COLSUM_W'(NR)) begin
        n_failed = n_failed + 1;
        $display("  FAIL: col %0d pulse was %0d, want %0d", j, first_val[j], NR);
      end
    end
    $display("[3] column skew pulse    : %0d checks, %0d fail  (latency %0d..%0d, %0d distinct)",
             n_checked - c_before, n_failed - f_before,
             lat_of(0), lat_of(NC-1), NP);
    flush();

    // =========================================================================
    // Phase 4: against the golden model, at full 16x14 scale.
    //
    // Vectors and expectations from model/gen_vectors.py, i.e. from
    // gemm_int8.gemm_tile_hw(): 25-bit A-port packing, 48-bit truncation,
    // borrow-corrected extraction, CASCADE_DEPTH grouping. Weights in the file
    // are RAW and include -128, so the hardware clamp is exercised and a
    // removed clamp fails here too.
    //
    // The file's expectation is additionally compared against the testbench's
    // own dot product for every vector. Those two references are independent;
    // if they disagree the fault is in the file indexing or in the model, and
    // saying so is more useful than a red RTL check.
    // =========================================================================
    c_before = n_checked;
    f_before = n_failed;
    for (i = 0; i < 16; i = i + 1) mmem[i] = 32'h0;
    $readmemh("build/vectors/meta.hex", mmem, 0, 8);
    if (mmem[0] !== MAGIC) begin
      $display(" FAIL   build/vectors/meta.hex missing or stale (magic %0h, want %0h)",
               mmem[0], MAGIC);
      $fatal(1, "tb_sa_array: run `python3 model/gen_vectors.py` first");
    end
    nt = mmem[1];
    pv = mmem[2];
    if (mmem[3] !== NR || mmem[4] !== NC || mmem[5] !== K_PACK ||
        mmem[6] !== CASCADE_DEPTH || mmem[7] !== COLSUM_W) begin
      $display(" FAIL   vector set built for ROWS=%0d COLS=%0d K=%0d DEPTH=%0d OUT_W=%0d; this build is %0d/%0d/%0d/%0d/%0d",
               mmem[3], mmem[4], mmem[5], mmem[6], mmem[7],
               NR, NC, K_PACK, CASCADE_DEPTH, COLSUM_W);
      $fatal(1, "tb_sa_array: vector set does not match sa_pkg");
    end
    if (nt < 1 || nt > MAXT || pv < 1 || nt * pv > MAXV) begin
      $display(" FAIL   vector set is %0d tiles x %0d vectors, outside 1..%0d / 1..%0d",
               nt, pv, MAXT, MAXV);
      $fatal(1, "tb_sa_array: vector set too large");
    end
    // Explicit end addresses, so a short file is an error rather than a
    // warning buried in the compile output and a tail of zeroed expectations.
    $readmemh("build/vectors/wgt.hex", wmem, 0, nt*NR*NC - 1);
    $readmemh("build/vectors/act.hex", amem, 0, nt*pv*NR - 1);
    $readmemh("build/vectors/exp.hex", emem, 0, nt*pv*NC - 1);

    mism = 0;
    for (t = 0; t < nt; t = t + 1) begin
      drain();
      for (i = 0; i < NR; i = i + 1)
        for (j = 0; j < NC; j = j + 1)
          W[i][j] = $signed(wmem[t*NR*NC + i*NC + j]);
      load_weights();

      for (v = 0; v < pv; v = v + 1) begin
        vi = t*pv + v;
        for (i = 0; i < NR; i = i + 1)
          a_vec[i] = $signed(amem[vi*NR + i]);
        // the testbench's own reference ...
        set_expect();
        // ... cross-checked against the model's, then the model's is the one
        // the hardware is held to.
        for (j = 0; j < NC; j = j + 1) begin
          n_checked = n_checked + 1;
          if (COLSUM_W'(e_now[j]) !== emem[vi*NC + j]) begin
            n_failed = n_failed + 1;
            mism     = mism + 1;
            if (mism <= 5)
              $display("  FAIL: vector %0d col %0d: model says %0d, tb dot product says %0d",
                       vi, j, $signed(emem[vi*NC + j]), e_now[j]);
          end
          e_now[j] = $signed(emem[vi*NC + j]);
        end
        issue(1'b1);
      end
      flush();
    end
    $display("[4] golden model %0dx%0d    : %0d checks, %0d fail  (%0d tiles x %0d vectors from gemm_int8.py)",
             NR, NC, n_checked - c_before, n_failed - f_before, nt, pv);

    // =========================================================================
    // Phase 5: the COLSUM_W corner, from both sides, with the clamp in the way.
    //
    // All NR rows of a column share one weight, so a column sum is NR times a
    // single product: 16 * 127 * 128 = 260096, which needs 19 bits signed and
    // is what COLSUM_W = 20 is sized for. -128 weights are included, and the
    // expectation is built from the clamped value, so a removed clamp fails.
    //
    // Even and odd columns are driven independently and both extremes are
    // checked afterwards: if a future change makes the corner unreachable this
    // phase would otherwise pass while proving nothing.
    // =========================================================================
    c_before  = n_checked;
    f_before  = n_failed;
    max_abs_e = 0;
    max_abs_o = 0;
    for (sv0 = 0; sv0 < 3; sv0 = sv0 + 1) begin
      for (sv1 = 0; sv1 < 3; sv1 = sv1 + 1) begin
        drain();
        for (i = 0; i < NR; i = i + 1) begin
          for (j = 0; j < NC; j = j + 1) begin
            if ((j % 2) == 0)
              W[i][j] = (sv0 == 0) ? WGT_MAX : ((sv0 == 1) ? WGT_MIN : -128);
            else
              W[i][j] = (sv1 == 0) ? WGT_MIN : ((sv1 == 1) ? WGT_MAX : -128);
          end
        end
        load_weights();

        for (av = 0; av < 6; av = av + 1) begin
          for (v = 0; v < 3; v = v + 1) begin
            for (i = 0; i < NR; i = i + 1)
              a_vec[i] = (av == 0) ? -128 :
                         (av == 1) ?  127 :
                         (av == 2) ? -127 :
                         (av == 3) ?    0 :
                         (av == 4) ?    1 : -1;
            set_expect();
            issue(1'b1);
          end
        end
        flush();
      end
    end
    n_checked = n_checked + 2;
    if (max_abs_e !== BOUND) begin
      n_failed = n_failed + 1;
      $display("  FAIL: even columns reached only %0d, expected the bound %0d",
               max_abs_e, BOUND);
    end
    if (max_abs_o !== BOUND) begin
      n_failed = n_failed + 1;
      $display("  FAIL: odd columns reached only %0d, expected the bound %0d",
               max_abs_o, BOUND);
    end
    $display("[5] COLSUM_W corners     : %0d checks, %0d fail  (max |colsum| = %0d)",
             n_checked - c_before, n_failed - f_before, max_abs_e);

    // =========================================================================
    // Phase 6: en = 0 must freeze the whole array -- 112 cells, every
    // alignment register, every output register and the horizontal traverse.
    //
    // Two stalls, as days 3 and 4:
    //   A  noise driven onto act_in, in-flight expectations discarded (the skew
    //      means their later rows were genuinely never applied)
    //   B  the activation source frozen with the datapath and nothing
    //      discarded, which is what day 11's AXI backpressure will do. With
    //      seven column-pairs in flight this is the one that pins the
    //      horizontal traverse across a stall, not just the vertical pipeline.
    // =========================================================================
    c_before = n_checked;
    f_before = n_failed;
    drain();
    for (i = 0; i < NR; i = i + 1)
      for (j = 0; j < NC; j = j + 1)
        W[i][j] = $urandom_range(0, 254) - 127;
    load_weights();
    for (v = 0; v < 30; v = v + 1) begin
      for (i = 0; i < NR; i = i + 1)
        a_vec[i] = $urandom_range(0, 255) - 128;
      set_expect();
      issue(1'b1);
    end

    for (j = 0; j < NC; j = j + 1) hold_s[j] = csum[j];
    for (i = 0; i < NR; i = i + 1) prev_act[i] = act_o[i];
    en = 1'b0;
    for (d = 0; d < 25; d = d + 1) begin
      for (i = 0; i < NR; i = i + 1)
        act[i] = ACT_W'($urandom_range(0, 255) - 128);
      @(posedge clk);
      #1;
      for (j = 0; j < NC; j = j + 1) begin
        n_checked = n_checked + 1;
        if (csum[j] !== COLSUM_W'(hold_s[j])) begin
          n_failed = n_failed + 1;
          if (n_failed - f_before <= 5)
            $display("  FAIL: en=0 but col %0d moved: %0d (was %0d)",
                     j, csum[j], hold_s[j]);
        end
      end
      for (i = 0; i < NR; i = i + 1) begin
        n_checked = n_checked + 1;
        if (act_o[i] !== ACT_W'(prev_act[i])) begin
          n_failed = n_failed + 1;
          if (n_failed - f_before <= 5)
            $display("  FAIL: en=0 but act_out[%0d] moved: %0d", i, act_o[i]);
        end
      end
    end
    en = 1'b1;
    // Discard the expectations that were in flight, and only these.
    for (i = 0; i <= LATMAX; i = i + 1) vldq[i] = 1'b0;
    act = '0;
    for (i = 0; i < NR; i = i + 1) begin
      a_vec[i] = 0;
      for (d = 0; d < NR; d = d + 1) ahist[d][i] = 0;
    end
    zero_expect();
    for (d = 0; d < 2 * SETTLE; d = d + 1) issue(1'b0);
    for (v = 0; v < 40; v = v + 1) begin
      for (i = 0; i < NR; i = i + 1)
        a_vec[i] = $urandom_range(0, 255) - 128;
      set_expect();
      issue(1'b1);
    end
    flush();

    // ---- stall B: freeze the activation source with the datapath ------------
    for (v = 0; v < 30; v = v + 1) begin
      for (i = 0; i < NR; i = i + 1)
        a_vec[i] = $urandom_range(0, 255) - 128;
      set_expect();
      issue(1'b1);
    end
    for (j = 0; j < NC; j = j + 1) hold_s[j] = csum[j];
    for (i = 0; i < NR; i = i + 1) prev_act[i] = act_o[i];
    en = 1'b0;
    for (d = 0; d < 20; d = d + 1) begin
      @(posedge clk);                    // act, ahist and the queue all held
      #1;
      for (j = 0; j < NC; j = j + 1) begin
        n_checked = n_checked + 1;
        if (csum[j] !== COLSUM_W'(hold_s[j])) begin
          n_failed = n_failed + 1;
          if (n_failed - f_before <= 5)
            $display("  FAIL: stall B, col %0d moved: %0d", j, csum[j]);
        end
      end
      for (i = 0; i < NR; i = i + 1) begin
        n_checked = n_checked + 1;
        if (act_o[i] !== ACT_W'(prev_act[i])) begin
          n_failed = n_failed + 1;
          if (n_failed - f_before <= 5)
            $display("  FAIL: stall B, act_out[%0d] moved: %0d", i, act_o[i]);
        end
      end
    end
    en = 1'b1;
    // Everything mid-flight must come out exactly as it would have without the
    // stall: the horizontal traverse and the group alignment both held, so all
    // seven column-pairs are still on the vectors they were on.
    for (v = 0; v < 40; v = v + 1) begin
      for (i = 0; i < NR; i = i + 1)
        a_vec[i] = $urandom_range(0, 255) - 128;
      set_expect();
      issue(1'b1);
    end
    flush();
    $display("[6] en=0 stall           : %0d checks, %0d fail",
             n_checked - c_before, n_failed - f_before);

    // =========================================================================
    // Phase 7: wgt_shift_en = 0 with noise on all NP serial ports. The 224
    // stored weights must not move, so the running results must not change.
    // =========================================================================
    c_before = n_checked;
    f_before = n_failed;
    drain();
    for (i = 0; i < NR; i = i + 1)
      for (j = 0; j < NC; j = j + 1)
        W[i][j] = $urandom_range(0, 254) - 127;
    load_weights();
    for (v = 0; v < 80; v = v + 1) begin
      for (p = 0; p < NP; p = p + 1)
        wser[p] = WGT_W'($urandom_range(0, 255) - 128);   // noise, wsh low
      for (i = 0; i < NR; i = i + 1)
        a_vec[i] = $urandom_range(0, 255) - 128;
      set_expect();
      issue(1'b1);
    end
    wser = '0;
    flush();
    $display("[7] wgt_shift_en gating  : %0d checks, %0d fail",
             n_checked - c_before, n_failed - f_before);

    // =========================================================================
    // Phase 8: the horizontal traverse, measured directly.
    //
    // act_out[i] must be act_in[i] delayed by exactly NP = 7 cycles, the same
    // count for every row. Two samples per cycle: before the edge act_out must
    // still show the value driven NP edges ago, after it the value driven NP-1
    // edges ago. The pair kills a traverse that is 6 or 8 deep and one that is
    // combinational, and doing it per row kills a row crossed with its
    // neighbour -- which would leave one column-pair summing two different
    // activation vectors while every number stayed in range.
    // =========================================================================
    c_before = n_checked;
    f_before = n_failed;
    act = '0;
    @(posedge clk);
    #1;
    for (d = 0; d <= NP; d = d + 1)
      for (i = 0; i < NR; i = i + 1) hq[d][i] = 0;
    for (cyc = 0; cyc < 150; cyc = cyc + 1) begin
      for (d = NP; d > 0; d = d - 1)
        for (i = 0; i < NR; i = i + 1) hq[d][i] = hq[d-1][i];
      for (i = 0; i < NR; i = i + 1) begin
        hq[0][i] = $urandom_range(0, 255) - 128;
        act[i]   = ACT_W'(hq[0][i]);
      end
      #1;
      for (i = 0; i < NR; i = i + 1) begin
        n_checked = n_checked + 1;
        if (act_o[i] !== ACT_W'(hq[NP][i])) begin
          n_failed = n_failed + 1;
          if (n_failed - f_before <= 5)
            $display("  FAIL: act_out[%0d] = %0d before the edge, want %0d (traverse is not %0d registers)",
                     i, act_o[i], hq[NP][i], NP);
        end
      end
      @(posedge clk);
      #1;
      for (i = 0; i < NR; i = i + 1) begin
        n_checked = n_checked + 1;
        if (act_o[i] !== ACT_W'(hq[NP-1][i])) begin
          n_failed = n_failed + 1;
          if (n_failed - f_before <= 5)
            $display("  FAIL: act_out[%0d] = %0d, want %0d (act_in delayed %0d cycles)",
                     i, act_o[i], hq[NP-1][i], NP);
        end
      end
    end
    $display("[8] horizontal traverse  : %0d checks, %0d fail  (%0d cycles per row)",
             n_checked - c_before, n_failed - f_before, NP);

    // =========================================================================
    // Phase 9: all NP weight chains, each exactly 2*NR deep, measured at once.
    //
    // wgt_out[p] must be wgt_in[p] delayed by 32 shift cycles, independently
    // per port. A port that is 31 or 33 deep misplaces every weight in its
    // column; a port that reads its neighbour's input makes two columns
    // identical. Distinct random streams per port catch both.
    // =========================================================================
    c_before = n_checked;
    f_before = n_failed;
    act = '0;
    // Empty the chains first. They still hold phase 7's weights, and a model
    // that starts at zero against hardware that does not reports NW-1 failures
    // that say nothing about the depth being measured.
    wsh  = 1'b1;
    wser = '0;
    for (d = 0; d < NW; d = d + 1) begin
      @(posedge clk);
      #1;
    end
    for (p = 0; p < NP; p = p + 1)
      for (i = 0; i < NW; i = i + 1) wq[p][i] = 0;
    for (d = 0; d < 3 * NW; d = d + 1) begin
      // Values stay inside [-127,127] so the clamp does not alter them and this
      // phase measures depth alone; the clamp itself is phases 4 and 5's job.
      for (p = 0; p < NP; p = p + 1) begin
        v = $urandom_range(0, 254) - 127;
        wser[p] = WGT_W'(v);
        // Shift the model first, then clock: after the edge the value presented
        // to this edge occupies stage 0, so stage NW-1 holds the value
        // presented NW-1 edges ago. The other order makes a chain of NW-1 or
        // NW+1 look correct.
        for (s = NW-1; s > 0; s = s - 1) wq[p][s] = wq[p][s-1];
        wq[p][0] = v;
      end
      @(posedge clk);
      #1;
      for (p = 0; p < NP; p = p + 1) begin
        n_checked = n_checked + 1;
        if (wgt_o[p] !== WGT_W'(wq[p][NW-1])) begin
          n_failed = n_failed + 1;
          if (n_failed - f_before <= 5)
            $display("  FAIL: wgt_out[%0d] = %0d, want %0d (wgt_in delayed %0d shifts)",
                     p, wgt_o[p], wq[p][NW-1], NW);
        end
      end
    end
    // The chains must also stand still when told to.
    wsh = 1'b0;
    for (d = 0; d < 12; d = d + 1) begin
      for (p = 0; p < NP; p = p + 1)
        wser[p] = WGT_W'($urandom_range(0, 255) - 128);
      @(posedge clk);
      #1;
      for (p = 0; p < NP; p = p + 1) begin
        n_checked = n_checked + 1;
        if (wgt_o[p] !== WGT_W'(wq[p][NW-1])) begin
          n_failed = n_failed + 1;
          if (n_failed - f_before <= 5)
            $display("  FAIL: wgt_out[%0d] moved with wgt_shift_en low: %0d", p, wgt_o[p]);
        end
      end
    end
    wser = '0;
    $display("[9] weight chain depth   : %0d checks, %0d fail",
             n_checked - c_before, n_failed - f_before);

    // =========================================================================
    $display("---------------------------------------------------------");
    if (n_failed == 0)
      $display(" PASS   %0d checks, 0 failures", n_checked);
    else
      $display(" FAIL   %0d checks, %0d failures", n_checked, n_failed);
    $display("=========================================================");

    if (n_checked < 250000)
      $fatal(1, "tb_sa_array: only %0d checks ran; the run was truncated", n_checked);
    if (n_failed != 0) $fatal(1, "tb_sa_array: %0d failures", n_failed);
    $finish;
  end

  // Watchdog: a deadlocked run must not hang CI forever.
  initial begin
    #2_000_000_000;
    $display(" FAIL   tb_sa_array: timeout");
    $fatal(1, "timeout");
  end

endmodule
